- name: install nginx
  apt:
    pkg: nginx
    state: "{{ nginx_state }}"
    update_cache: "{{ apt_update_cache }}"
    

- name: create site dir
  file:
    path: "/var/www/html/{{ project_name }}/src"
    state: directory
    mode: "{{ site_dir_mode }}"
    owner: "{{ site_dir_owner }}"
    group: "{{ site_dir_group }}"
